# Example Processing Config
job_id: proc_16qam_32g_lms_01
system: # Optional: Can be defined here or loaded from metadata
  # samplerate_dac_hz: 92e9 # Often needed for reference
  samplerate_adc_hz: 92e9
  symbolrate_baud: 32e9
input_dtype: npy # Matches the output format of generation example
input_file_path: "data/generated/gen_16qam_32g_01_seq.npy" # Placeholder - OVERRIDE VIA SCRIPT ARG
associated_metadata_path: "data/generated/gen_16qam_32g_01_meta.yaml" # Placeholder - OVERRIDE VIA SCRIPT ARG
output_dir: "data/processed/proc_16qam_32g_lms_01" # Placeholder - OVERRIDE VIA SCRIPT ARG
save_intermediate: false
seed: 1999
pipeline:
  - function: resampling
    target_rate_hz: 64e9 # Target sample rate
    filter_type: polyphase
  - function: cd_compensation
    fiber_length_km: 80
    dispersion_ps_nm_km: 17.0
    center_wavelength_nm: 1550.0
  # - function: timing_recovery # Placeholder for a timing block
  #   method: gardner
  #   samples_per_symbol_in: 2
  - function: equalization
    method: lms
    num_taps: 41 # Example for DP-16QAM (might need MIMO version)
    step_size: 5e-4
    num_iterations_train: 16384 # Train on first 16k symbols
    mode: training # Start in training mode
  - function: metrics_calculation
    metrics_to_calculate: [evm, ber] # Calculate EVM and BER
    # reference_sequence_path: "path/to/reference_bits.npy" # Needs path to original bits
    skip_symbols_start: 16384 # Skip training symbols for metrics