"""
Signal I/O and file management utilities.

Functions
---------
save_npz(signal, path, *, compressed=True, include_cache=False)
    Save a Signal to a compressed NumPy archive (.npz).

load_npz(path, *, device="cpu") -> Signal
    Load a Signal from a .npz archive written by save_npz.

File layout
-----------
The .npz file contains the following named entries:

  ``samples``              - IQ sample array  (always present)
  ``source_bits``          - source bit array  (omitted if None)
  ``source_symbols``       - source symbol array  (omitted if None)
  ``resolved_symbols``     - cached symbol array  (only with include_cache=True)
  ``resolved_bits``        - cached bit array     (only with include_cache=True)
  ``__metadata__``         - zero-d object array holding a YAML string with all
                             scalar fields.
  ``__frame_metadata__``   - zero-d object array holding a YAML string with the
                             serialised SingleCarrierFrame fields (omitted when
                             the signal was not generated from a frame).
  ``frame_payload_symbols`` - frame payload symbols array  (omitted if no frame)
  ``frame_pilot_symbols``   - frame pilot symbols array    (omitted if no frame/pilots)
  ``frame_payload_bits``    - frame payload bits array     (omitted if no frame)
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Union

import numpy as np
import yaml

from . import backend as _backend

if TYPE_CHECKING:
    from .core import Signal

# -----------------------------------------------------------------------------
# Internal constants
# -----------------------------------------------------------------------------

# Scalar / primitive metadata fields to round-trip through YAML
_META_FIELDS: tuple[str, ...] = (
    "sampling_rate",
    "symbol_rate",
    "signal_type",
    "mod_scheme",
    "mod_order",
    "mod_unipolar",
    "mod_rz",
    "pulse_shape",
    "filter_span",
    "rrc_rolloff",
    "rc_rolloff",
    "duty_cycle",
    "rise_time",
    "spectral_domain",
    "physical_domain",
    "center_frequency",
    "digital_frequency_offset",
)

# Optional array fields (not always present)
_OPTIONAL_ARRAY_FIELDS: tuple[str, ...] = (
    "source_bits",
    "source_symbols",
)

# Derived / cached array fields (only written when include_cache=True)
_CACHE_FIELDS: tuple[str, ...] = ("resolved_symbols", "resolved_bits")


# -----------------------------------------------------------------------------
# Public API
# -----------------------------------------------------------------------------


def save_npz(
    signal: Signal,
    path: Union[str, Path],
    *,
    compressed: bool = True,
    include_cache: bool = False,
) -> None:
    """
    Save a :class:`~commstools.Signal` to a NumPy archive (.npz).

    Parameters
    ----------
    signal : Signal
        The signal to persist.
    path : str or Path
        Destination path.  A ``.npz`` extension is appended automatically
        if absent.
    compressed : bool, default True
        Use :func:`numpy.savez_compressed` (zlib).  Set to ``False`` to use
        the uncompressed :func:`numpy.savez` (faster write, larger file).
    include_cache : bool, default False
        Also save ``resolved_symbols`` and ``resolved_bits`` if present.
        These can be recomputed from the signal, so they are omitted by
        default to keep file sizes small.

    Notes
    -----
    When the signal was generated by :meth:`SingleCarrierFrame.to_signal`,
    the originating frame is serialised into the archive
    (``__frame_metadata__`` + ``frame_payload_symbols`` etc.).  On load,
    :func:`load_npz` reconstructs the frame and re-attaches it so that
    :meth:`Signal.correct_timing` and frame-aware equalizer workflows work
    identically to a freshly generated signal.

    Examples
    --------
    >>> save_npz(sig, "capture.npz")
    >>> save_npz(sig, "capture", compressed=False, include_cache=True)
    """
    path = Path(path)
    if path.suffix != ".npz":
        path = path.with_suffix(".npz")

    # -------------------------------------------------------------------------
    # Collect arrays
    # -------------------------------------------------------------------------
    arrays: dict[str, np.ndarray] = {
        "samples": _backend.to_device(signal.samples, "CPU")
    }

    for field in _OPTIONAL_ARRAY_FIELDS:
        arr = getattr(signal, field, None)
        if arr is not None:
            arrays[field] = _backend.to_device(arr, "CPU")

    if include_cache:
        for field in _CACHE_FIELDS:
            arr = getattr(signal, field, None)
            if arr is not None:
                arrays[field] = _backend.to_device(arr, "CPU")

    # -------------------------------------------------------------------------
    # Serialise originating SingleCarrierFrame (if present)
    # -------------------------------------------------------------------------
    # The frame holds the complete transmit-side description (structure map,
    # pilot masks, preamble sequence, generated payload/pilot symbols).
    # Saving it ensures that correct_timing() and pilot extraction all work
    # after a save/load round-trip without requiring the caller to keep a
    # reference to the original frame object.
    frame = signal.frame
    if frame is not None:
        # All public fields are JSON-serializable primitives; nested Preamble
        # is a Pydantic model and is also captured by model_dump().
        # _frame_type stores the class name so load_npz can reconstruct the
        # correct type when multiple frame classes exist (SingleCarrierFrame,
        # future OFDMFrame, etc.) without hardcoding the class.
        frame_dict = frame.model_dump(mode="json")
        frame_dict["_frame_type"] = type(frame).__name__
        yaml_frame = yaml.dump(frame_dict, default_flow_style=False, allow_unicode=True)
        arrays["__frame_metadata__"] = np.array(yaml_frame, dtype=object)

        # Save the generated symbol/bit arrays that live in PrivateAttrs and
        # are NOT reproduced by model_dump().  Payload symbols and bits are
        # random; pilot symbols are deterministic but cheap to cache anyway.
        for npz_key, frame_attr in (
            ("frame_payload_symbols", "payload_symbols"),
            ("frame_pilot_symbols", "pilot_symbols"),
            ("frame_payload_bits", "payload_bits"),
        ):
            arr = getattr(frame, frame_attr, None)
            if arr is not None:
                arrays[npz_key] = _backend.to_device(arr, "CPU")

    # -------------------------------------------------------------------------
    # Build metadata dict and serialise to YAML
    # -------------------------------------------------------------------------
    meta: dict = {f: getattr(signal, f) for f in _META_FIELDS}
    yaml_str = yaml.dump(meta, default_flow_style=False, allow_unicode=True)

    # Store as a zero-d object array so np.savez treats it as a single entry
    arrays["__metadata__"] = np.array(yaml_str, dtype=object)

    # -------------------------------------------------------------------------
    # Write
    # -------------------------------------------------------------------------
    save_fn = np.savez_compressed if compressed else np.savez
    save_fn(path, **arrays)


def load_npz(
    path: Union[str, Path],
    *,
    device: str = "auto",
) -> Signal:
    """
    Load a :class:`~commstools.Signal` from a .npz archive.

    Parameters
    ----------
    path : str or Path
        Path to the ``.npz`` file.  A ``.npz`` extension is appended
        automatically if absent.
    device : {"auto", "cpu", "gpu"}, default "auto"
        Target device after loading.  ``"auto"`` moves to GPU when CuPy is
        available, otherwise stays on CPU.

    Returns
    -------
    Signal

    Notes
    -----
    If the archive contains ``__frame_metadata__`` (written by
    :func:`save_npz` when the signal originated from a frame), the
    originating frame is reconstructed (class determined by the
    ``_frame_type`` key embedded in the metadata) and re-attached as
    ``sig.frame``.  This makes :meth:`Signal.correct_timing` and
    frame-aware equalizer workflows work without any extra arguments.

    Examples
    --------
    >>> sig = load_npz("capture.npz")           # auto: GPU if available
    >>> sig_cpu = load_npz("capture.npz", device="cpu")
    >>> sig_gpu = load_npz("capture.npz", device="gpu")
    """
    from .core import Signal

    path = Path(path)
    if path.suffix != ".npz":
        path = path.with_suffix(".npz")

    # allow_pickle=True is required to read the zero-d object array that
    # holds the YAML string; no arbitrary Python objects are loaded.
    data = np.load(path, allow_pickle=True)

    # -------------------------------------------------------------------------
    # Parse YAML metadata
    # -------------------------------------------------------------------------
    yaml_str = str(data["__metadata__"])
    meta: dict = yaml.safe_load(yaml_str)

    # Build Signal constructor kwargs
    # -------------------------------------------------------------------------
    kwargs: dict = {f: meta.get(f) for f in _META_FIELDS}
    kwargs["samples"] = data["samples"]

    for field in _OPTIONAL_ARRAY_FIELDS:
        if field in data:
            kwargs[field] = data[field]

    sig = Signal(**kwargs)

    # -------------------------------------------------------------------------
    # Restore cached arrays (bypass re-computation if present in file)
    # -------------------------------------------------------------------------
    for field in _CACHE_FIELDS:
        if field in data:
            setattr(sig, field, data[field])

    # -------------------------------------------------------------------------
    # Reconstruct originating frame (if serialised)
    # -------------------------------------------------------------------------
    if "__frame_metadata__" in data:
        from . import core as _core  # noqa: PLC0415

        frame_dict = yaml.safe_load(str(data["__frame_metadata__"]))
        frame_type_name = frame_dict.pop("_frame_type", "SingleCarrierFrame")

        # Registry of known frame classes — extend here as new frame types land.
        _FRAME_CLASSES = {
            "SingleCarrierFrame": _core.SingleCarrierFrame,
        }
        frame_cls = _FRAME_CLASSES.get(frame_type_name)
        if frame_cls is None:
            raise ValueError(
                f"Cannot reconstruct frame of type {frame_type_name!r}: "
                "unknown frame class. Extend _FRAME_CLASSES in io.py."
            )
        frame = frame_cls(**frame_dict)

        # Inject the cached symbol/bit arrays back into the frame's PrivateAttrs
        # so that frame.payload_symbols, frame.pilot_symbols, frame.payload_bits
        # return the original generated data without re-randomising.
        if "frame_payload_symbols" in data:
            frame._payload_symbols = data["frame_payload_symbols"]
        if "frame_pilot_symbols" in data:
            frame._pilot_symbols = data["frame_pilot_symbols"]
        if "frame_payload_bits" in data:
            frame._payload_bits = data["frame_payload_bits"]

        sig.frame = frame

    # -------------------------------------------------------------------------
    # Move to target device
    # -------------------------------------------------------------------------
    target = device.lower()
    if target == "auto":
        target = "gpu" if _backend.is_cupy_available() else "cpu"
    sig = sig.to(target)
    return sig
